# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
    - package-ecosystem: 'npm' # See documentation for possible values
      directory: '/' # Location of package manifests
      schedule:
          interval: 'daily'
      ignore:
          - dependency-name: '@wowfinder/assets'
            versions: ['0.x']
          - dependency-name: '@wowfinder/ts-enums'
            versions: ['0.x']
          - dependency-name: '@wowfinder/ts-utils'
            versions: ['0.x']
    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: 'weekly'
