logFilters:
  - level: discard
    pattern: eslint-plugin-deprecation
  - level: discard
    pattern: eslint-plugin-istanbul
  - level: discard
    pattern: eslint-plugin-misc
  - level: discard
    pattern: eslint-config-standard

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.9.1.cjs
