import { RawSkills } from '@wowfinder/asset-schemas';

const skillsBonusDefaultBuilder: Partial<RawSkills> = {} as const;

const skillsBonusFullBuilder: RawSkills = {
    acrobatics: 1,
    appraise: 2,
    athletics: 3,
    bluff: 4,
    alchemy: 5,
    blacksmithing: 6,
    cooking: 7,
    inscription: 8,
    jewelcrafting: 9,
    leatherworking: 10,
    tailoring: 11,
    technology: 12,
    woodworking: 13,
    diplomacy: 14,
    disarm: 15,
    disguise: 16,
    escape: 17,
    handleAnimal: 18,
    heal: 19,
    intimidate: 20,
    linguistics: 21,
    arcane: 22,
    dungeons: 23,
    engineering: 24,
    geography: 25,
    history: 26,
    nature: 27,
    nobility: 28,
    planes: 29,
    religion: 30,
    perception: 31,
    act: 32,
    comedy: 33,
    dance: 34,
    keyboard: 35,
    percussion: 36,
    sing: 37,
    speech: 38,
    string: 39,
    wind: 40,
    butchery: 41,
    enchanting: 42,
    fishing: 43,
    herbalism: 44,
    lumbering: 45,
    mining: 46,
    skinning: 47,
    ride: 48,
    senseMotive: 49,
    sleight: 50,
    stealth: 51,
};

export { skillsBonusDefaultBuilder, skillsBonusFullBuilder };
