import { Skill, Stat } from '@wowfinder/ts-enums';
import { SkillSpec } from './SkillSpec';
import { mkSkill } from './helpers';

const Skills: { [key in Skill]: SkillSpec } = {
    acrobatics: mkSkill(Skill.acrobatics, Stat.dexterity, null, false, -2),
    athletics: mkSkill(Skill.athletics, Stat.strength),
    appraise: mkSkill(Skill.appraise, Stat.intelligence),
    bluff: mkSkill(Skill.bluff, Stat.charisma),
    alchemy: mkSkill(Skill.alchemy, Stat.intelligence, Stat.dexterity, true),
    blacksmithing: mkSkill(
        Skill.blacksmithing,
        Stat.intelligence,
        Stat.dexterity,
        true,
    ),
    cooking: mkSkill(Skill.cooking, Stat.intelligence, Stat.dexterity, true),
    inscription: mkSkill(
        Skill.inscription,
        Stat.intelligence,
        Stat.dexterity,
        true,
    ),
    jewelcrafting: mkSkill(
        Skill.jewelcrafting,
        Stat.intelligence,
        Stat.dexterity,
        true,
    ),
    leatherworking: mkSkill(
        Skill.leatherworking,
        Stat.intelligence,
        Stat.dexterity,
        true,
    ),
    tailoring: mkSkill(
        Skill.tailoring,
        Stat.intelligence,
        Stat.dexterity,
        true,
    ),
    technology: mkSkill(
        Skill.technology,
        Stat.intelligence,
        Stat.dexterity,
        true,
    ),
    woodworking: mkSkill(
        Skill.woodworking,
        Stat.intelligence,
        Stat.dexterity,
        true,
    ),
    diplomacy: mkSkill(Skill.diplomacy, Stat.charisma),
    disarm: mkSkill(Skill.disarm, Stat.dexterity, null, true),
    disguise: mkSkill(Skill.disguise, Stat.charisma),
    escape: mkSkill(Skill.escape, Stat.dexterity, null, false, -2),
    handleAnimal: mkSkill(Skill.handleAnimal, Stat.charisma),
    heal: mkSkill(Skill.heal, Stat.wisdom),
    intimidate: mkSkill(
        Skill.intimidate,
        Stat.charisma,
        Stat.strength,
        false,
        2,
    ),
    linguistics: mkSkill(Skill.linguistics, Stat.intelligence, null, true),
    arcane: mkSkill(Skill.arcane, Stat.intelligence, Stat.wisdom, true),
    dungeons: mkSkill(Skill.dungeons, Stat.intelligence, Stat.wisdom, true),
    engineering: mkSkill(
        Skill.engineering,
        Stat.intelligence,
        Stat.wisdom,
        true,
    ),
    geography: mkSkill(Skill.geography, Stat.intelligence, Stat.wisdom, true),
    history: mkSkill(Skill.history, Stat.intelligence, Stat.wisdom, true),
    nature: mkSkill(Skill.nature, Stat.intelligence, Stat.wisdom, true),
    nobility: mkSkill(Skill.nobility, Stat.intelligence, Stat.wisdom, true),
    planes: mkSkill(Skill.planes, Stat.intelligence, Stat.wisdom, true),
    religion: mkSkill(Skill.religion, Stat.intelligence, Stat.wisdom, true),
    perception: mkSkill(Skill.perception, Stat.wisdom),
    act: mkSkill(Skill.act, Stat.charisma),
    comedy: mkSkill(Skill.comedy, Stat.charisma),
    dance: mkSkill(Skill.dance, Stat.charisma),
    keyboard: mkSkill(Skill.keyboard, Stat.charisma),
    percussion: mkSkill(Skill.percussion, Stat.charisma),
    sing: mkSkill(Skill.sing, Stat.charisma),
    speech: mkSkill(Skill.speech, Stat.charisma),
    string: mkSkill(Skill.string, Stat.charisma),
    wind: mkSkill(Skill.wind, Stat.charisma),
    butchery: mkSkill(Skill.butchery, Stat.wisdom, Stat.intelligence, true),
    enchanting: mkSkill(Skill.enchanting, Stat.wisdom, Stat.intelligence, true),
    fishing: mkSkill(Skill.fishing, Stat.wisdom, Stat.intelligence, true),
    herbalism: mkSkill(Skill.herbalism, Stat.wisdom, Stat.intelligence, true),
    lumbering: mkSkill(Skill.lumbering, Stat.wisdom, Stat.intelligence, true),
    mining: mkSkill(Skill.mining, Stat.wisdom, Stat.intelligence, true),
    skinning: mkSkill(Skill.skinning, Stat.wisdom, Stat.intelligence, true),
    ride: mkSkill(Skill.ride, Stat.dexterity),
    senseMotive: mkSkill(Skill.senseMotive, Stat.wisdom),
    sleight: mkSkill(Skill.sleight, Stat.dexterity, null, true),
    stealth: mkSkill(Skill.stealth, Stat.dexterity, null, false, -4),
};

export { Skills };
