name: Continous Integration

on:
    push:
        branches:
            - main
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
    build:
        name: Continous Integration
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Use Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: 20
            - name: Setup internal dependency registry
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  registry-url: https://npm.pkg.github.com/
                  scope: '@wowfinder'
                  always-auth: true
                  token: ${{ secrets.GITHUB_TOKEN }}
            - name: Install dependencies
              run: yarn
            - name: Lint validation
              run: yarn lint
            - name: Module compilation and build
              run: yarn build
            - name: Test and coverage
              run: yarn jest --coverage
            - name: SonarCloud Scan
              uses: SonarSource/sonarcloud-github-action@master
              env:
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
