# Based on example on https://github.com/marketplace/actions/github-action-for-yarn

name: CI

on: [push]

jobs:
    build:
        name: Validation
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: 20
            - name: Yarn cache clean
              uses: Borales/actions-yarn@v5.0.0
              with:
                  cmd: cache clean
            - name: Yarn install
              uses: Borales/actions-yarn@v5.0.0
              with:
                  cmd: install --force
            - name: Yarn prepush script
              uses: Borales/actions-yarn@v5.0.0
              with:
                  cmd: checks:standard
